# Generated by Django 5.2.11 on 2026-02-07 00:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_contingencia', models.CharField(choices=[('NORMAL', '🟢 Normal - Sin Restricciones'), ('FASE_1', '🟡 Fase 1 - Restricción 20% Vehículos'), ('FASE_2', '🔴 Fase 2 - Restricción 50% Vehículos')], default='NORMAL', max_length=10, verbose_name='Estado de Contingencia Ambiental')),
                ('mensaje_alerta', models.TextField(blank=True, help_text='Mensaje que aparecerá en el panel de los choferes y administración.')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Estado de Contingencia',
                'verbose_name_plural': 'Configuración Estado de Contingencia',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('licencia', models.CharField(max_length=50, unique=True, verbose_name='No. de Licencia')),
                ('vigencia_licencia', models.DateField(verbose_name='Vigencia de Licencia')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nUnidad', models.CharField(editable=False, max_length=20, unique=True, verbose_name='No. Unidad (U#)')),
                ('placas', models.CharField(max_length=15, unique=True, verbose_name='Placas')),
                ('descripcion_vehiculo', models.CharField(default='Sin descripción', help_text='Ej. Camión Freightliner Blanco 10 Ton', max_length=200, verbose_name='Descripción del Vehículo')),
                ('no_serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='No. de Serie')),
                ('no_motor', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de Motor')),
                ('tarjeta_circulacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarjeta de Circulación')),
                ('vencimiento_placa', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Placa')),
                ('tipo_permiso_stc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Permiso STC')),
                ('nombre_aseguradora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aseguradora')),
                ('tipo_cobertura_seguro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Cobertura')),
                ('poliza_seguro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Póliza')),
                ('vencimiento_poliza', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Póliza')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('submarca', models.CharField(max_length=50, verbose_name='Submarca')),
                ('modelo_anio', models.PositiveIntegerField(verbose_name='Modelo (Año)')),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta')], default='CAMION', max_length=20)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad (kg)')),
                ('en_servicio', models.BooleanField(default=True, verbose_name='¿En servicio?')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha Adquisición')),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, verbose_name='Km Actual')),
                ('ultimo_pago_tenencia', models.DateField(blank=True, null=True, verbose_name='Último pago Tenencia')),
                ('holograma', models.CharField(choices=[('00', '00'), ('0', '0'), ('1', '1'), ('2', '2')], default='00', editable=False, max_length=2)),
                ('vencimiento_verificacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('ALMACEN', 'Almacén'), ('RUTAS', 'Rutas / Logística'), ('ADMIN', 'Administrador')], max_length=20)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100, verbose_name='Tipo de Servicio (ej. Preventivo)')),
                ('fecha_realizado', models.DateField(auto_now_add=True)),
                ('km_en_servicio', models.PositiveIntegerField(verbose_name='Kilometraje en ese momento')),
                ('proximo_km', models.PositiveIntegerField(verbose_name='Próximo servicio (Kilómetros)')),
                ('proxima_fecha', models.DateField(verbose_name='Próximo servicio (Fecha)')),
                ('completado', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='dashboard.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precio_litro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propina', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='GastoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('tipo', models.CharField(choices=[('Verificación', '🔍 Verificación'), ('Tenencia', '💰 Tenencia'), ('Seguro', '🛡️ Seguro'), ('Mantenimiento', '🛠️ Mantenimiento (Refacciones/Anticongelante)'), ('Otro', '📦 Otro')], max_length=20, verbose_name='Tipo de Gasto')),
                ('detalle', models.CharField(help_text='Ej: Compra de anticongelante o correas', max_length=255, verbose_name='Detalle del Gasto')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo ($)')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generales', to='dashboard.unidad')),
            ],
            options={
                'verbose_name': 'Gasto de Unidad',
                'verbose_name_plural': 'Control de Gastos de Unidades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CheckListDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('km_salida', models.PositiveIntegerField()),
                ('km_llegada', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_aceite', models.BooleanField(default=True, verbose_name='Aceite OK')),
                ('nivel_anticongelante', models.BooleanField(default=True, verbose_name='Anticongelante OK')),
                ('presion_llantas', models.BooleanField(default=True, verbose_name='Llantas OK')),
                ('luces_funcionan', models.BooleanField(default=True, verbose_name='Luces OK')),
                ('limpieza_vidrios', models.BooleanField(default=True, verbose_name='Limpiaparabrisas OK')),
                ('combustible_inicial', models.CharField(max_length=20, verbose_name='Nivel Combustible (ej. 1/4)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_viaje', models.PositiveIntegerField(editable=False, verbose_name='No. de Viaje')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_viaje', models.CharField(choices=[('VENTA', 'Venta Normal'), ('TALLER', 'Taller / Mantenimiento'), ('COMBUSTIBLE', 'Cargar Combustible'), ('RECOLECCION', 'Recoger Mercancía')], default='VENTA', max_length=20)),
                ('estado_actual', models.CharField(choices=[('ESPERA', 'En Espera (Programado)'), ('TRANSITO', 'En Tránsito (Validado)'), ('FINALIZADO', 'Finalizado (Llegada a CMA)')], default='ESPERA', max_length=20)),
                ('hora_salida_cedis', models.TimeField(blank=True, null=True, verbose_name='Salida CMA')),
                ('hora_llegada_cedis', models.TimeField(blank=True, null=True, verbose_name='Regreso CMA')),
                ('mercancia_revisada', models.BooleanField(default=False, verbose_name='¿Mercancía Revisada?')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.operador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.unidad')),
            ],
            options={
                'permissions': [('can_validate_merchandise', 'Puede validar salida de mercancía')],
            },
        ),
        migrations.CreateModel(
            name='PedidoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_aspel', models.CharField(max_length=50, verbose_name='Nota/Factura/Cotización')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Cliente')),
                ('zona', models.IntegerField(verbose_name='Zona')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('PAGADO', 'Pagado'), ('POR_COBRAR', 'Por Cobrar')], max_length=20)),
                ('peso_kg', models.IntegerField(default=0)),
                ('hora_llegada_cliente', models.TimeField(blank=True, null=True)),
                ('hora_salida_cliente', models.TimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='dashboard.viaje')),
            ],
        ),
    ]
