# Generated by Django 5.2.11 on 2026-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocombustible',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Combustible', 'verbose_name_plural': 'Registros de Combustible'},
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='tipo_combustible',
            field=models.CharField(choices=[('MAGNA', 'Magna (Verde)'), ('PREMIUM', 'Premium (Roja)'), ('DIESEL', 'Diesel (Negro)')], default='MAGNA', max_length=20, verbose_name='Tipo de Combustible'),
        ),
        migrations.AlterField(
            model_name='registrocombustible',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='registrocombustible',
            name='precio_litro',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='registrocombustible',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Propina (Opcional)'),
        ),
        migrations.AlterField(
            model_name='registrocombustible',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total ($)'),
        ),
    ]
