# Generated by Django 5.2.11 on 2026-02-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_registrocombustible_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='puesto',
            field=models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('ALMACEN', 'Almacén'), ('RUTAS', 'Rutas / Logística'), ('ADMIN', 'Administrador'), ('CHOFER', 'Chofer')], max_length=20),
        ),
    ]
