# Generated by Django 5.2.11 on 2026-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_personal_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='capacidad_tanque',
            field=models.PositiveIntegerField(default=100, verbose_name='Capacidad Tanque (Litros)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='tipo_combustible_unidad',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina')], default='DIESEL', max_length=10, verbose_name='Tipo de Motor'),
        ),
    ]
