# Generated by Django 5.2.11 on 2026-02-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_unidad_capacidad_tanque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocombustible',
            old_name='kilometraje',
            new_name='kilometraje_actual',
        ),
    ]
