# Generated by Django 5.2.11 on 2026-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_kilometraje_registrocombustible_kilometraje_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocombustible',
            name='evidencia_antes',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias_combustible/', verbose_name='Evidencia Antes (Tablero)'),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='evidencia_despues',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias_combustible/', verbose_name='Evidencia Después (Tablero)'),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
