# Generated by Django 5.2.11 on 2026-02-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_registrocombustible_evidencia_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='nombre_corto',
            field=models.CharField(blank=True, help_text="Identificador rápido para modales y listas (ej. 'La Perrona')", max_length=50, null=True, verbose_name='Nombre Corto'),
        ),
    ]
