# Generated by Django 5.2.11 on 2026-02-16 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_unidad_nombre_corto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gastounidad',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chofer Responsable'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='gastos_evidencias/', verbose_name='Evidencia (PDF/Foto)'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km al momento del gasto'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='motivo_multa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Multa'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='poliza_seguro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nueva Póliza'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='tipo_cobertura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cobertura'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='tipo_permiso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Permiso'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='vigencia_permiso',
            field=models.DateField(blank=True, null=True, verbose_name='Nueva Vigencia'),
        ),
        migrations.AlterField(
            model_name='gastounidad',
            name='detalle',
            field=models.CharField(help_text='Ej: Verificación 1er Semestre, Multa por velocidad', max_length=255, verbose_name='Detalle del Gasto'),
        ),
        migrations.AlterField(
            model_name='gastounidad',
            name='tipo',
            field=models.CharField(choices=[('Verificación', '🔍 Verificación'), ('Tenencia', '💰 Tenencia'), ('Seguro', '🛡️ Seguro'), ('Mantenimiento', '🛠️ Mantenimiento (Preventivo/Correctivo)'), ('Multa', '👮 Multa'), ('Permiso', '📄 Permiso'), ('Peaje', '🛣️ Peaje'), ('Placas', '🚗 Placas'), ('Otro', '📦 Otro')], max_length=20, verbose_name='Tipo de Gasto'),
        ),
    ]
