# Generated by Django 5.2.11 on 2026-02-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_gastounidad_aseguradora_gastounidad_chofer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='titular_poliza',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la Póliza'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre_corto',
            field=models.CharField(blank=True, help_text="Identificador rápido para modales y listas (ej. 'Rojita')", max_length=50, null=True, verbose_name='Nombre Interno'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta')], default='CAMIONETA', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_combustible_unidad',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('MAGNA', 'Magna'), ('PREMIUM', 'Premium')], default='PREMIUM', max_length=10, verbose_name='Tipo de Motor'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_permiso_stc',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Permiso STC'),
        ),
    ]
