# Generated by Django 5.2.11 on 2026-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_unidad_titular_poliza_alter_unidad_nombre_corto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='personal',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='personal',
            name='apellido_paterno',
            field=models.CharField(default='SinAp', max_length=100, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='nombre',
            field=models.CharField(default='DefaultName', max_length=100, verbose_name='Nombre(s)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_combustible_unidad',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina')], default='GASOLINA', max_length=10, verbose_name='Tipo de Motor'),
        ),
    ]
