# Generated by Django 5.2.11 on 2026-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_personal_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlogistica',
            name='restringir_h1',
            field=models.CharField(choices=[('PAR', 'Pares Restringidos'), ('NON', 'Nones Restringidos'), ('NA', 'No Aplica')], default='NA', max_length=3, verbose_name='Paridad Restringida (Holograma 1)'),
        ),
        migrations.AlterField(
            model_name='configuracionlogistica',
            name='estado_contingencia',
            field=models.CharField(choices=[('NORMAL', '🟢 Normal - Sin Restricciones'), ('PREVENTIVA', '⚪ Preventiva - Alerta '), ('FASE_1', '🟡 Fase 1 - Restricción 20% Vehículos'), ('FASE_2', '🔴 Fase 2 - Restricción 50% Vehículos')], default='NORMAL', max_length=10, verbose_name='Estado de Contingencia Ambiental'),
        ),
    ]
