# Generated by Django 5.2.11 on 2026-02-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_configuracionlogistica_restringir_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
