# Generated by Django 5.2.11 on 2026-02-23 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_personal_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('kilometraje', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('nivel_gasolina', models.IntegerField(choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], verbose_name='Nivel de Gasolina')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción detallada del servicio')),
                ('responsable_mantenimiento', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=10, verbose_name='Responsable de mantenimiento')),
                ('nombre_responsable_externo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del externo (si aplica)')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre de solicitante')),
                ('firma_solicitante_base64', models.TextField(blank=True, null=True, verbose_name='Firma Solicitante (Base64)')),
                ('nombre_autorizante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de autorizante')),
                ('firma_autorizante_base64', models.TextField(blank=True, null=True, verbose_name='Firma Autorizante (Base64)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Chofer')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
