# Generated by Django 5.2.11 on 2026-02-24 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_ordenservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='doc_factura',
            field=models.FileField(blank=True, null=True, upload_to='unidades/docs/', verbose_name='Copia Factura (PDF/IMG)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='doc_permisos',
            field=models.FileField(blank=True, null=True, upload_to='unidades/docs/', verbose_name='Permisos Federales/STC (PDF/IMG)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='doc_poliza',
            field=models.FileField(blank=True, null=True, upload_to='unidades/docs/', verbose_name='Póliza Seguro (PDF/IMG)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='doc_tarjeta_circulacion',
            field=models.FileField(blank=True, null=True, upload_to='unidades/docs/', verbose_name='Tarjeta Circulación (PDF/IMG)'),
        ),
        migrations.CreateModel(
            name='ChecklistUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora de Registro')),
                ('nivel_combustible', models.IntegerField(choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], verbose_name='Nivel Combustible')),
                ('aceite_motor', models.BooleanField(default=False, verbose_name='Nivel Aceite Motor OK')),
                ('anticongelante', models.BooleanField(default=False, verbose_name='Nivel Anticongelante/Agua OK')),
                ('llantas_birlos', models.BooleanField(default=False, verbose_name='Presión Llantas y Ajuste Birlos OK')),
                ('carroceria_golpes', models.BooleanField(default=False, verbose_name='Carrocería sin golpes evidentes')),
                ('luces', models.BooleanField(default=False, verbose_name='Luces (altas, bajas, cuartos, dir.) OK')),
                ('cinturon', models.BooleanField(default=False, verbose_name='Cinturón de seguridad OK')),
                ('equipo_seguridad', models.BooleanField(default=False, verbose_name='Gato, palanca, cruceta, refacción, triángulo OK')),
                ('documentacion', models.BooleanField(default=False, verbose_name='Circulación, Póliza, Licencia OK')),
                ('frenos', models.BooleanField(default=False, verbose_name='Freno pie y mano OK')),
                ('bateria_arranque', models.BooleanField(default=False, verbose_name='Batería y Arranque OK')),
                ('limpiaparabrisas', models.BooleanField(default=False, verbose_name='Limpiaparabrisas OK')),
                ('claxon', models.BooleanField(default=False, verbose_name='Claxon OK')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Falla reportada')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Chofer')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Checklist Diario de Unidad',
                'verbose_name_plural': 'Checklists Diarios',
                'ordering': ['-fecha', '-hora_registro'],
            },
        ),
    ]
