# Generated by Django 5.2.11 on 2026-02-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_unidad_doc_factura_unidad_doc_permisos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Zona (Ej. Norte, Sur, Centro)')),
                ('colonias', models.TextField(blank=True, help_text='Listado de colonias principales', null=True, verbose_name='Colonias que Abarca')),
                ('tiempo_traslado_minutos', models.PositiveIntegerField(verbose_name='Tiempo Medio Traslado (mins)')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distancia Media (Km) desde Sucursal')),
                ('tarifa_flete', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo Base de Flete ($)')),
                ('costo_maniobra', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo Maniobra Adicional ($)')),
            ],
            options={
                'verbose_name': 'Zona de Entrega',
                'verbose_name_plural': 'Zonas de Entrega',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='viaje',
            name='folio_nota_factura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Folios (Facturas/Notas)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='km_llegada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km Llegada'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='km_salida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km Salida'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zonaentrega', verbose_name='Zona de Entrega Principal'),
        ),
    ]
