# Generated by Django 5.2.11 on 2026-02-24 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_zonaentrega_viaje_folio_nota_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioLlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de Llanta')),
                ('medida', models.CharField(max_length=50, verbose_name='Medida (Ej. 295/80R22.5)')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie/DOT')),
                ('posicion', models.CharField(choices=[('DI1', 'Delantera Izquierda 1'), ('DD1', 'Delantera Derecha 1'), ('TI1', 'Trasera Izquierda 1'), ('TD1', 'Trasera Derecha 1'), ('TI2', 'Trasera Izquierda 2 (Doble)'), ('TD2', 'Trasera Derecha 2 (Doble)'), ('REFACCION', 'Refacción')], max_length=20, verbose_name='Posición en Unidad')),
                ('profundidad_piso_mm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Profundidad de Piso (mm)')),
                ('fecha_instalacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Instalación')),
                ('km_instalacion', models.PositiveIntegerField(verbose_name='Km al Instalar')),
                ('activa', models.BooleanField(default=True, verbose_name='Instalada Actualmente')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Condición / Observaciones')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llantas', to='dashboard.unidad', verbose_name='Unidad Asignada')),
            ],
            options={
                'verbose_name': 'Inventario de Llanta',
                'verbose_name_plural': 'Inventario de Llantas',
                'unique_together': {('unidad', 'posicion', 'activa')},
            },
        ),
    ]
