# Generated by Django 5.2.11 on 2026-02-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_inventariollanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_satisfecho', models.BooleanField(default=True, verbose_name='¿Cliente Satisfecho con la Entrega?')),
                ('motivo_insatisfaccion', models.CharField(choices=[('OK', 'Entregado sin problemas'), ('MERCANCIA_DANADA', 'Mercancía Dañada / Faltante'), ('TIEMPO_ALTO', 'Tardanza en entrega'), ('MALA_ATENCION', 'Mala atención del personal'), ('CLIENTE_AUSENTE', 'Cliente no se encontraba / Local cerrado'), ('OTRO', 'Otro (Especificar en observaciones)')], default='OK', max_length=50, verbose_name='Motivo Principal (Si aplica)')),
                ('tiempo_espera_cliente_minutos', models.PositiveIntegerField(default=0, verbose_name='Tiempo de descarga/espera con cliente (minutos)')),
                ('hubo_incidencia_transporte', models.BooleanField(default=False, verbose_name='¿Hubo incidente de transporte?')),
                ('desc_incidencia_transporte', models.TextField(blank=True, null=True, verbose_name='Describa falla mecánica o imprevisto en ruta')),
                ('nombre_quien_recibe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de quien recibe la mercancía')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales / Detalle del problema')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='dashboard.viaje', verbose_name='Viaje Asociado')),
            ],
            options={
                'verbose_name': 'Evaluación de Entrega',
                'verbose_name_plural': 'Evaluaciones de Entregas',
            },
        ),
    ]
