# Generated by Django 5.2.11 on 2026-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_evaluacionentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='proximo_servicio_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Servicio Recomendado (Fecha)'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='proximo_servicio_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo Servicio Recomendado (Km)'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo (Afinación, Cambio de aceite, etc.)'), ('CORRECTIVO', 'Correctivo (Reparación de falla/siniestro)')], default='CORRECTIVO', max_length=15, verbose_name='Tipo de Mantenimiento'),
        ),
    ]
