# Generated by Django 5.2.11 on 2026-02-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_ordenservicio_proximo_servicio_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaentrega',
            name='codigos_postales',
            field=models.TextField(blank=True, help_text='Separados por coma', null=True, verbose_name='Códigos Postales'),
        ),
    ]
