# Generated by Django 5.2.11 on 2026-03-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_zonaentrega_codigos_postales'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaentrega',
            name='color_hex',
            field=models.CharField(default='#3388ff', help_text='Color para identificar la zona en el mapa', max_length=7, verbose_name='Color en Mapa'),
        ),
        migrations.AddField(
            model_name='zonaentrega',
            name='geojson_data',
            field=models.TextField(blank=True, help_text='Información geográfica de la zona', null=True, verbose_name='Polígonos de la Zona (GeoJSON)'),
        ),
    ]
