# Generated by Django 5.2.11 on 2026-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_zonaentrega_color_hex_zonaentrega_geojson_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostalCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, verbose_name='Código Postal')),
                ('asentamiento', models.CharField(max_length=200, verbose_name='Colonia/Asentamiento')),
                ('tipo_asentamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Código Postal',
                'verbose_name_plural': 'Códigos Postales',
                'ordering': ['codigo', 'asentamiento'],
            },
        ),
    ]
