# Generated by Django 5.2.11 on 2026-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_codigopostalcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base_chofer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sueldo Base Chofer ($)')),
                ('sueldo_base_chalan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sueldo Base Chalán ($)')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuraciones Generales',
            },
        ),
    ]
