# Generated by Django 5.2.11 on 2026-03-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_configuraciongeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariollanta',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de la Llanta ($)'),
        ),
    ]
