# Generated by Django 5.2.11 on 2026-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_inventariollanta_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariollanta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento (por DOT)'),
        ),
    ]
