# Generated by Django 5.2.11 on 2026-03-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_inventariollanta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='limite_seguridad_llanta_mm',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=4, verbose_name='Límite Seguridad Llanta (mm)'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='vida_util_estimada_llanta_km',
            field=models.PositiveIntegerField(default=100000, verbose_name='Vida Útil Estimada Llanta (km)'),
        ),
    ]
