# Generated by Django 5.2.11 on 2026-03-07 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_configuraciongeneral_limite_seguridad_llanta_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistunidad',
            name='km_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje Actual'),
        ),
        migrations.CreateModel(
            name='MedicionNeumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Medición')),
                ('km_medicion', models.PositiveIntegerField(verbose_name='Kilometraje al Medir')),
                ('presion_psi', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Presión (PSI)')),
                ('profundidad_mm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Profundidad (mm)')),
                ('llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='dashboard.inventariollanta', verbose_name='Llanta')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_neumaticos', to='dashboard.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Medición de Neumático',
                'verbose_name_plural': 'Mediciones de Neumáticos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
