# Generated by Django 5.2.11 on 2026-03-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_checklistunidad_km_actual_medicionneumatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariollanta',
            name='profundidad_inicial_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Profundidad Inicial (mm)'),
        ),
        migrations.AddField(
            model_name='medicionneumatico',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Causa Probable / Observaciones'),
        ),
        migrations.AlterField(
            model_name='inventariollanta',
            name='profundidad_piso_mm',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Profundidad de Piso Actual (mm)'),
        ),
    ]
