# Generated by Django 5.2.11 on 2026-03-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_inventariollanta_profundidad_inicial_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='numero_llantas',
            field=models.PositiveIntegerField(choices=[(4, '4 Llantas'), (6, '6 Llantas')], default=6, verbose_name='Número de Llantas'),
        ),
    ]
