# Generated by Django 5.2.11 on 2026-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_unidad_numero_llantas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='sueldo_base_chalan',
        ),
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='sueldo_base_chofer',
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='sueldo_semanal_chalan',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='Sueldo Semanal Chalán ($)'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='sueldo_semanal_chofer',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10, verbose_name='Sueldo Semanal Chofer ($)'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tiempo_descarga_promedio_min',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo fijo agregado a cada viaje por maniobras.', verbose_name='Tiempo de Descarga Promedio (min)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('AUTO', 'Automóvil'), ('MOTO', 'Motocicleta')], default='CAMIONETA', max_length=20),
        ),
    ]
