# Generated by Django 5.2.11 on 2026-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_configuraciongeneral_sueldo_base_chalan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta')], default='CAMIONETA', max_length=20),
        ),
    ]
