# Generated by Django 5.2.11 on 2026-03-16 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_unidad_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sae', models.CharField(max_length=20, unique=True, verbose_name='ID SAE (ERP)')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social / Nombre')),
                ('telefono_principal', models.CharField(max_length=15, verbose_name='Teléfono Principal')),
            ],
            options={
                'verbose_name': 'Cliente (SAE)',
                'verbose_name_plural': 'Clientes (SAE)',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(choices=[('INTERNO_FLOTILLA', 'Ruta A: Unidad Flotilla'), ('INTERNO_PERSONAL', 'Ruta B: Vehículo Personal'), ('PROVEEDOR_EXTERNO', 'Ruta C: Proveedor Externo')], default='INTERNO_FLOTILLA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido / Rechazado')], default='PENDIENTE', max_length=20)),
                ('peso_asignado_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Asignado (kg)')),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_entrega', models.DateTimeField(blank=True, null=True)),
                ('maniobra_especial', models.BooleanField(default=False, verbose_name='¿Se realizó maniobra especial?')),
                ('descripcion_maniobra', models.TextField(blank=True, null=True, verbose_name='Detalle de maniobra/propina')),
                ('observaciones_entrega', models.TextField(blank=True, null=True, verbose_name='Observaciones del chofer')),
                ('foto_ticket_firmado', models.ImageField(blank=True, null=True, upload_to='entregas/tickets/', verbose_name='Foto Ticket Firmado')),
            ],
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='limite_peso_vehiculo_personal_kg',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Límite Peso Vehículo Personal (kg)'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tolerancia_peso_ruta_kg',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Tolerancia de Peso en Ruta (kg)'),
        ),
        migrations.CreateModel(
            name='EvidenciaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='entregas/material/', verbose_name='Foto Material en Sitio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_material', to='dashboard.despacho')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Nulo para avisos globales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, verbose_name='Alias de la Obra (Ej. Casa Blanca)')),
                ('calle_numero', models.CharField(max_length=255, verbose_name='Calle y Número')),
                ('referencias', models.TextField(blank=True, null=True, verbose_name='Referencias de Ubicación')),
                ('nombre_receptor', models.CharField(max_length=150, verbose_name='Nombre de quien recibe')),
                ('telefono_receptor', models.CharField(max_length=15, verbose_name='Teléfono del Receptor')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Obra Activa')),
                ('fecha_ultimo_pedido', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='dashboard.cliente')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.zonaentrega', verbose_name='Zona de Entrega')),
            ],
            options={
                'verbose_name': 'Obra / Dirección de Entrega',
                'verbose_name_plural': 'Obras / Directorio de Obras',
                'ordering': ['-fecha_ultimo_pedido', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_sae', models.CharField(max_length=50, unique=True, verbose_name='Folio SAE')),
                ('peso_total_estimado_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Total (kg)')),
                ('evidencia_ticket', models.FileField(blank=True, null=True, upload_to='pedidos/tickets/', verbose_name='Evidencia Ticket (PDF/IMG)')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_PREPARACION', 'En Preparación'), ('ASIGNADO_A_RUTA', 'Asignado a Ruta'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('ENTREGA_PARCIAL', 'Entrega Parcial'), ('REPROGRAMADO', 'Reprogramado')], default='REGISTRADO', max_length=20)),
                ('es_urgente', models.BooleanField(default=False, verbose_name='¿Es Urgente / Flete Pagado?')),
                ('maniobra_aceptada', models.BooleanField(default=False, verbose_name='Maniobra a pie de camión aceptada')),
                ('recoleccion_parcial', models.BooleanField(default=False, verbose_name='Recolección parcial en mostrador')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='dashboard.cliente')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='dashboard.obra')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='dashboard.pedido'),
        ),
        migrations.CreateModel(
            name='ViajeNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_personal_info', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info Vehículo Personal (Motos/Particular)')),
                ('proveedor_externo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor Externo (Ej. Sergio Almacen)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('chalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_ayuda', to=settings.AUTH_USER_MODEL, verbose_name='Chalán')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_asignados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.unidad', verbose_name='Unidad Flotilla')),
            ],
        ),
        migrations.AddField(
            model_name='despacho',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='dashboard.viajenuevo'),
        ),
    ]
