# Generated by Django 5.2.11 on 2026-03-16 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_cliente_despacho_alter_operador_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='operador',
            name='puesto',
            field=models.CharField(default='Operador', max_length=100, verbose_name='Puesto / Departamento'),
        ),
        migrations.AddField(
            model_name='operador',
            name='usa_sistema',
            field=models.BooleanField(default=False, verbose_name='¿Usa el sistema operativo regularmente?'),
        ),
        migrations.AddField(
            model_name='operador',
            name='usuario_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_directorio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operador',
            name='licencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de Licencia'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='vigencia_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de Licencia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_PREPARACION', 'En Preparación'), ('ASIGNADO_A_RUTA', 'Asignado a Ruta'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('ENTREGA_PARCIAL', 'Entrega Parcial'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='REGISTRADO', max_length=20),
        ),
    ]
