# Generated by Django 5.2.11 on 2026-03-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_operador_email_operador_puesto_operador_usa_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_direccion_manual',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Entrega (Manual)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre_manual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Cliente (Manual)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_telefono_manual',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Cliente (Manual)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta (Débito/Crédito)'), ('POR_COBRAR', 'Por Cobrar (Contra entrega)'), ('CREDITO', 'Crédito SAE')], default='EFECTIVO', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones_mostrador',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones General / Campo Extra'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos_entregados_parcial',
            field=models.TextField(blank=True, null=True, verbose_name='Productos entregados en Mostrador'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='dashboard.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='folio_sae',
            field=models.CharField(max_length=50, unique=True, verbose_name='Folio SAE / Ticket'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='Opcional para entregas rápidas en mostrador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='dashboard.obra'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('CAMION', 'Camión (Ruta Pesada)'), ('CAMIONETA_3_5', 'Camioneta 3.5 Ton'), ('CAMIONETA_1_5', 'Camioneta 1.5 Ton'), ('AUTO', 'Auto / Sedán'), ('MOTO', 'Motocicleta (Express)')], default='CAMIONETA', max_length=20),
        ),
    ]
