# Generated by Django 5.2.11 on 2026-03-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_pedido_cliente_direccion_manual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_mostrador',
            field=models.BooleanField(default=False, verbose_name='¿Es Cliente Mostrador?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_sae',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID SAE (ERP)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social / Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_principal',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Principal'),
        ),
    ]
