# Generated by Django 5.2.11 on 2026-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_cliente_options_cliente_es_mostrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaentrega',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
    ]
