# Generated by Django 5.2.11 on 2026-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_zonaentrega_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='obra',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='obra',
            name='entre_calles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entre Calles'),
        ),
        migrations.AddField(
            model_name='obra',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='obra',
            name='zona_aprobada',
            field=models.BooleanField(default=True, help_text='Si se desmarca, el pedido quedará bloqueado hasta revisión.', verbose_name='¿Zona autorizada por Logística?'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='calle_numero',
            field=models.CharField(max_length=255, verbose_name='Calle y Número Ext/Int'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre_receptor',
            field=models.CharField(max_length=150, verbose_name='Nombre de quien recibe (Residente/Maestro/Cliente)'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='referencias',
            field=models.TextField(blank=True, null=True, verbose_name='Referencias Visuales (Color de fachada, portón, etc.)'),
        ),
    ]
