# Generated by Django 5.2.11 on 2026-03-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_pedido_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tipos_ticket_json',
            field=models.JSONField(blank=True, default=list, help_text="Formato: [{'nombre': '...', 'prefijo': '...'}, ...]", null=True, verbose_name='Tipos de Ticket (Prefijos)'),
        ),
    ]
