# Generated by Django 5.2.11 on 2026-03-23 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_configuraciongeneral_tipos_ticket_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SISTEMA', 'Sistema'), ('PEDIDO', 'Pedido'), ('MANTENIMIENTO', 'Mantenimiento'), ('ALERTA', 'Alerta / Urgente')], default='SISTEMA', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
