# Generated by Django 5.2.11 on 2026-03-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaentrega',
            name='route_geojson',
            field=models.TextField(blank=True, null=True, verbose_name='Ruta Oficial (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='zonaentrega',
            name='route_waypoints',
            field=models.TextField(blank=True, null=True, verbose_name='Waypoints de la Ruta (JSON)'),
        ),
    ]
