# Generated by Django 5.2.11 on 2026-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_zonaentrega_route_geojson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='roles_secundarios',
            field=models.CharField(blank=True, help_text='Separados por coma (Ej. MOSTRADOR,CAJA,LOGISTICA)', max_length=255, null=True),
        ),
    ]
