# Generated by Django 5.2.11 on 2026-03-26 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_personal_roles_secundarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gastounidad',
            name='acompanante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_acompanante', to=settings.AUTH_USER_MODEL, verbose_name='Acompañante/Chalán'),
        ),
        migrations.AddField(
            model_name='gastounidad',
            name='responsabilidad_compartida',
            field=models.BooleanField(default=False, verbose_name='¿Es responsabilidad compartida?'),
        ),
        migrations.AlterField(
            model_name='gastounidad',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_chofer', to=settings.AUTH_USER_MODEL, verbose_name='Chofer Responsable'),
        ),
    ]
