# Generated by Django 5.2.11 on 2026-04-03 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_gastounidad_acompanante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonaentrega',
            options={'verbose_name': 'Zona de Entrega', 'verbose_name_plural': 'Zonas de Entrega'},
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='foto_ticket_firmado',
        ),
        migrations.AddField(
            model_name='despacho',
            name='cantidad_productos_despacho',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en este Despacho'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='fecha_surtido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='foto_ticket_marcado',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/tickets/', verbose_name='Foto Ticket Marcado/Tachado/Firmado'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='productos_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle de productos (Manual)'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='surtido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_surtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despacho',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_entregada_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Entregado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_total_productos',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Productos (SAE)'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO_SURTIDO', 'Asignado a Surtido'), ('SURTIDO_COMPLETO', 'Surtido Completo (Patio)'), ('LISTO_PARA_RUTA', 'Listo para Ruta'), ('VALIDADO_ADMIN', 'Validado (Administrativo)'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO_PARCIAL', 'Entrega Parcial'), ('ENTREGADO_TOTAL', 'Entregado Total'), ('RECHAZO_PARCIAL', 'Rechazo Parcial'), ('CANCELADO', 'Cancelado'), ('PROVEEDOR_PENDIENTE', 'Proveedor: Pendiente'), ('PROVEEDOR_CONFIRMADO', 'Proveedor: Confirmado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado (Mostrador)'), ('DESPACHOS_GENERADOS', 'Despachos Generados'), ('EN_PROCESO', 'En Proceso (Al menos uno en ruta)'), ('ENTREGADO_PARCIAL', 'Entregado Parcial'), ('ENTREGADO_TOTAL', 'Entregado Total'), ('CANCELADO', 'Cancelado / Cerrado con Ajuste'), ('CERRADO', 'Cierre Administrativo')], default='REGISTRADO', max_length=20),
        ),
    ]
