# Generated by Django 5.2.11 on 2026-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_zonaentrega_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='cantidad_productos_despacho',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='fecha_surtido',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='fecha_validacion',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='foto_ticket_marcado',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='productos_detalle',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='surtido_por',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='validado_por',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_entregada_total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_total_productos',
        ),
        migrations.AddField(
            model_name='despacho',
            name='foto_ticket_firmado',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/tickets/', verbose_name='Foto Ticket Firmado'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido / Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_PREPARACION', 'En Preparación'), ('ASIGNADO_A_RUTA', 'Asignado a Ruta'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('ENTREGA_PARCIAL', 'Entrega Parcial'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='REGISTRADO', max_length=20),
        ),
    ]
