# Generated by Django 5.2.11 on 2026-04-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_despacho_cantidad_productos_despacho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos_entregados_parcial',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='recoleccion_parcial',
        ),
        migrations.AddField(
            model_name='pedido',
            name='articulos_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Artículos Totales (pzas/m/etc)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente / Registrado'), ('CREADO', 'Pedido Creado / Ingestado'), ('DESPACHOS_GENERADOS', 'Despachos Generados'), ('EN_PROCESO', 'En Proceso (Múltiples Despachos)'), ('PARCIAL', 'Entregado Parcial (Queda Saldo)'), ('ENTREGADO', 'Entregado Totalmente'), ('CERRADO', 'Cerrado Administrativamente')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='peso_total_estimado_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso Total (kg)'),
        ),
    ]
