# Generated by Django 5.2.11 on 2026-04-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_pedido_productos_entregados_parcial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='cantidad_articulos_asignados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Artículos Asignados'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='cantidad_articulos_rechazados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Artículos Rechazados'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Surtido'), ('ASIGNADO_SURTIDO', 'Surtido en Proceso'), ('SURTIDO_COMPLETO', 'Surtido Físico Completo'), ('LISTO_PARA_RUTA', 'Listo para Ruta'), ('EN_RUTA', 'En Ruta de Entrega'), ('CONFIRMADO', 'Entregado / Confirmado'), ('RECHAZO_PARCIAL', 'Entregado Parcialmente'), ('CANCELADO', 'Cancelado / Rechazo Total')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='peso_asignado_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso Asignado (kg)'),
        ),
        migrations.CreateModel(
            name='AlertaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('RECHAZO_PARCIAL', 'Rechazo Parcial en Sitio'), ('RECHAZO_TOTAL', 'Rechazo Total en Sitio'), ('DIRECCION_INCORRECTA', 'Dirección Incorrecta / No Localizada'), ('AUSENCIA_CLIENTE', 'Cliente Ausente / Local Cerrado'), ('OTRO', 'Incidencia General')], max_length=25)),
                ('comentarios', models.TextField(verbose_name='Descripción de la incidencia')),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Alerta Gestionada?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_levantadas', to=settings.AUTH_USER_MODEL)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='dashboard.despacho')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
