# Generated by Django 5.2.11 on 2026-04-06 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_despacho_cantidad_articulos_asignados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajenuevo',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado / Programado'), ('EN_CURSO', 'En Curso / Salida'), ('REPROGRAMADO', 'Reprogramado (Vencido)'), ('FINALIZADO', 'Finalizado')], default='CREADO', max_length=20),
        ),
        migrations.AddField(
            model_name='viajenuevo',
            name='fecha_viaje',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Programada'),
        ),
        migrations.AddField(
            model_name='viajenuevo',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Llegada'),
        ),
        migrations.AddField(
            model_name='viajenuevo',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida'),
        ),
    ]
