# Generated by Django 5.2.11 on 2026-04-07 06:46

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_viajenuevo_estado_viajenuevo_fecha_viaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viajenuevo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='viajenuevo',
            name='fecha_viaje',
            field=models.DateField(default=dashboard.models.ViajeNuevo.get_local_date, verbose_name='Fecha Programada'),
        ),
    ]
