# Generated by Django 5.2.11 on 2026-04-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_viajenuevo_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='surtidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_surtidos', to='dashboard.personal'),
        ),
    ]
