# Generated by Django 5.2.11 on 2026-04-09 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_despacho_surtidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viajenuevo',
            name='es_reprogramado',
            field=models.BooleanField(default=False, help_text='Indica si la ruta fue reprogramada en algún punto'),
        ),
        migrations.AddField(
            model_name='viajenuevo',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viajenuevo',
            name='usuario_cancelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viajenuevo',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado / Programado'), ('EN_CURSO', 'En Curso / Salida'), ('REPROGRAMADO', 'Reprogramado (Vencido)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=20),
        ),
    ]
