# Generated by Django 5.2.11 on 2026-04-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_viajenuevo_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('rfc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RFC')),
                ('especialidad', models.CharField(choices=[('FLETES', 'Fletes / Transportista'), ('MANTENIMIENTO', 'Taller / Mantenimiento'), ('COMBUSTIBLE', 'Gasolinera / Combustible'), ('LLANTAS', 'Llantera / Neumáticos'), ('REFACCIONES', 'Refaccionaria'), ('OTROS', 'Otros Servicios')], default='OTROS', max_length=20, verbose_name='Especialidad')),
                ('contacto_nombre', models.CharField(max_length=150, verbose_name='Nombre del Contacto')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Física')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web / Catálogo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
