# Generated by Django 5.2.11 on 2026-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='sitio_web',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='especialidad',
            field=models.CharField(choices=[('FLETES', 'Fletes / Transportista'), ('MANTENIMIENTO', 'Taller / Mantenimiento'), ('MERCANCIAS', 'Mercancias Varios'), ('MERCANCIAS CON FLETE', 'Mercancias con Flete'), ('OTROS', 'Otros Servicios')], default='OTROS', max_length=20, verbose_name='Especialidad'),
        ),
    ]
