# Generated by Django 5.2.11 on 2026-04-09 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_remove_proveedor_sitio_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajenuevo',
            name='proveedor_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to='dashboard.proveedor', verbose_name='Proveedor de Servicio'),
        ),
        migrations.AlterField(
            model_name='viajenuevo',
            name='proveedor_externo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor Externo (Legacy/Manual)'),
        ),
    ]
