# Generated by Django 5.2.11 on 2026-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_viajenuevo_proveedor_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='hora_finalizacion_surtido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Surtido'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='hora_inicio_surtido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Surtido'),
        ),
    ]
