# Generated by Django 5.2.11 on 2026-04-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_despacho_hora_finalizacion_surtido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitud GPS'),
        ),
        migrations.AddField(
            model_name='obra',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitud GPS'),
        ),
        migrations.AddField(
            model_name='obra',
            name='ubicacion_verificada',
            field=models.BooleanField(default=False, verbose_name='¿Ubicación Verificada?'),
        ),
    ]
