# Generated by Django 5.2.11 on 2026-04-22 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_obra_latitud_obra_longitud_obra_ubicacion_verificada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Si se desmarca, sus unidades a cargo se repartirán entre otros choferes.', verbose_name='¿Está activo hoy?'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='responsable_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Mantenimiento'),
        ),
    ]
