# Generated by Django 5.2.11 on 2026-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_personal_esta_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistunidad',
            name='alerta_reversa',
            field=models.BooleanField(default=False, verbose_name='Alerta de Reversa OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='bandas_sujecion',
            field=models.BooleanField(default=False, verbose_name='Bandas de Sujeción / Matracas OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='lona',
            field=models.BooleanField(default=False, verbose_name='Lona en buen estado / Disponible'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='retrovisores',
            field=models.BooleanField(default=False, verbose_name='Espejos Retrovisores OK'),
        ),
    ]
