# Generated by Django 5.2.11 on 2026-04-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_checklistunidad_alerta_reversa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistunidad',
            name='aceite_caja',
            field=models.BooleanField(default=False, verbose_name='Aceite de Caja de Velocidades OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='aceite_diferencial',
            field=models.BooleanField(default=False, verbose_name='Aceite de Diferencial OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='aceite_direccion',
            field=models.BooleanField(default=False, verbose_name='Aceite de Dirección OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='clutch',
            field=models.BooleanField(default=False, verbose_name='Clutch / Embrague OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='limpieza_exteriores',
            field=models.CharField(choices=[('MALA', 'Mala'), ('REGULAR', 'Regular'), ('BUENA', 'Buena')], default='BUENA', max_length=10, verbose_name='Limpieza de Exteriores'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='limpieza_interiores',
            field=models.CharField(choices=[('MALA', 'Mala'), ('REGULAR', 'Regular'), ('BUENA', 'Buena')], default='BUENA', max_length=10, verbose_name='Limpieza de Interiores'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='liquido_frenos',
            field=models.BooleanField(default=False, verbose_name='Líquido de Frenos OK'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='documentacion',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto'), ('NO_CUENTA', 'No se cuenta')], default='COMPLETO', max_length=20, verbose_name='Circulación, Póliza, Licencia'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='equipo_seguridad',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto'), ('NO_CUENTA', 'No se cuenta')], default='COMPLETO', max_length=20, verbose_name='Gato, palanca, cruceta, refacción, triángulo'),
        ),
    ]
