# Generated by Django 5.2.11 on 2026-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_checklistunidad_aceite_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistunidad',
            name='agua_bateria',
            field=models.BooleanField(default=False, verbose_name='Agua de Batería OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='agua_limpiabrisas',
            field=models.BooleanField(default=False, verbose_name='Agua de Limpiaparabrisas OK'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpiaparabrisas',
            field=models.BooleanField(default=False, verbose_name='Limpiaparabrisas (Wipers) OK'),
        ),
    ]
