# Generated by Django 5.2.11 on 2026-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_checklistunidad_agua_bateria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistunidad',
            name='documentacion',
            field=models.CharField(choices=[('NO_CUENTA', 'No se cuenta'), ('INCOMPLETO', 'Incompleto'), ('COMPLETO', 'Completo')], default='COMPLETO', max_length=20, verbose_name='Circulación, Póliza, Licencia'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='equipo_seguridad',
            field=models.CharField(choices=[('NO_CUENTA', 'No se cuenta'), ('INCOMPLETO', 'Incompleto'), ('COMPLETO', 'Completo')], default='COMPLETO', max_length=20, verbose_name='Gato, palanca, cruceta, refacción, triángulo'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_exteriores',
            field=models.CharField(choices=[('MALA', 'Mala'), ('BUENA', 'Buena'), ('REGULAR', 'Regular')], default='BUENA', max_length=10, verbose_name='Limpieza de Exteriores'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_interiores',
            field=models.CharField(choices=[('MALA', 'Mala'), ('BUENA', 'Buena'), ('REGULAR', 'Regular')], default='BUENA', max_length=10, verbose_name='Limpieza de Interiores'),
        ),
    ]
