# Generated by Django 5.2.11 on 2026-04-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_checklistunidad_documentacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistunidad',
            name='fecha_revision_admin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión Admin'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='revisado_admin',
            field=models.BooleanField(default=False, verbose_name='Revisado por Administración'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='usuario_revision_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Admin que revisó'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_exteriores',
            field=models.CharField(choices=[('MALA', 'Mala'), ('REGULAR', 'Regular'), ('BUENA', 'Buena')], default='BUENA', max_length=10, verbose_name='Limpieza de Exteriores'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_interiores',
            field=models.CharField(choices=[('MALA', 'Mala'), ('REGULAR', 'Regular'), ('BUENA', 'Buena')], default='BUENA', max_length=10, verbose_name='Limpieza de Interiores'),
        ),
    ]
