# Generated by Django 5.2.11 on 2026-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_checklistunidad_fecha_revision_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistunidad',
            name='aceite_caja',
        ),
        migrations.RemoveField(
            model_name='checklistunidad',
            name='aceite_diferencial',
        ),
        migrations.RemoveField(
            model_name='checklistunidad',
            name='agua_bateria',
        ),
        migrations.RemoveField(
            model_name='checklistunidad',
            name='llantas_birlos',
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='birlos_ajuste',
            field=models.BooleanField(default=False, verbose_name='Ajuste Físico de Birlos'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='llantas_presion',
            field=models.BooleanField(default=False, verbose_name='Presión de Llantas (Visual)'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='urea',
            field=models.CharField(choices=[('NA', 'No aplica'), ('BAJO', 'Bajo'), ('ALTO', 'Alto')], default='NA', max_length=10, verbose_name='Nivel de Urea (AdBlue)'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_exteriores',
            field=models.CharField(choices=[('NO_REALIZADO', 'No Realizado'), ('REALIZADO', 'Realizado')], default='REALIZADO', max_length=20, verbose_name='Limpieza de Exteriores'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_interiores',
            field=models.CharField(choices=[('NO_REALIZADO', 'No Realizado'), ('REALIZADO', 'Realizado')], default='REALIZADO', max_length=20, verbose_name='Limpieza de Interiores'),
        ),
    ]
