# Generated by Django 5.2.11 on 2026-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_remove_checklistunidad_aceite_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdiario',
            name='nivel_agua_limpiabrisas',
            field=models.BooleanField(default=True, verbose_name='Agua Limpiabrisas OK'),
        ),
        migrations.AddField(
            model_name='checklistdiario',
            name='nivel_liquido_direccion',
            field=models.BooleanField(default=True, verbose_name='Liquido de Dirección OK'),
        ),
        migrations.AddField(
            model_name='checklistdiario',
            name='nivel_liquido_frenos',
            field=models.BooleanField(default=True, verbose_name='Liquido de Frenos OK'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='documentacion',
            field=models.CharField(choices=[('NO_CUENTA', 'No se cuenta'), ('INCOMPLETO', 'Incompleto'), ('COMPLETO', 'Completo')], default='NO_CUENTA', max_length=20, verbose_name='Circulación, Póliza, Licencia'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='equipo_seguridad',
            field=models.CharField(choices=[('NO_CUENTA', 'No se cuenta'), ('INCOMPLETO', 'Incompleto'), ('COMPLETO', 'Completo')], default='NO_CUENTA', max_length=20, verbose_name='Gato, palanca, cruceta, refacción, triángulo'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_exteriores',
            field=models.CharField(choices=[('NO_REALIZADO', 'No Realizado'), ('REALIZADO', 'Realizado')], default='NO_REALIZADO', max_length=20, verbose_name='Limpieza de Exteriores'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpieza_interiores',
            field=models.CharField(choices=[('NO_REALIZADO', 'No Realizado'), ('REALIZADO', 'Realizado')], default='NO_REALIZADO', max_length=20, verbose_name='Limpieza de Interiores'),
        ),
    ]
