# Generated by Django 5.2.11 on 2026-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_checklistdiario_nivel_agua_limpiabrisas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistunidad',
            name='epp_botas',
            field=models.BooleanField(default=False, verbose_name='Botas de seguridad OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='epp_casco',
            field=models.BooleanField(default=False, verbose_name='Casco de seguridad OK'),
        ),
        migrations.AddField(
            model_name='checklistunidad',
            name='epp_chaleco',
            field=models.BooleanField(default=False, verbose_name='Chaleco reflectivo OK'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='aceite_direccion',
            field=models.BooleanField(default=False, verbose_name='Nivel de Líquido de Dirección'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='aceite_motor',
            field=models.BooleanField(default=False, verbose_name='Nivel de Aceite de Motor'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='agua_limpiabrisas',
            field=models.BooleanField(default=False, verbose_name='Nivel de Líquido Limpiaparabrisas'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='anticongelante',
            field=models.BooleanField(default=False, verbose_name='Nivel de Anticongelante/Agua'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='carroceria_golpes',
            field=models.CharField(choices=[('OK', 'OK (Sin daños)'), ('GOLPE', 'Golpe'), ('RASPADURA', 'Raspadura'), ('OTROS', 'Otros')], default='OK', max_length=20, verbose_name='Estado de Carrocería'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='documentacion',
            field=models.CharField(choices=[('NO_CUENTA', 'No se cuenta'), ('INCOMPLETO', 'Incompleto'), ('COMPLETO', 'Completo')], default='NO_CUENTA', max_length=20, verbose_name='Tarjeta de circulación, Póliza, Licencia'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='limpiaparabrisas',
            field=models.BooleanField(default=False, verbose_name='Limpiaparabrisas OK'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='liquido_frenos',
            field=models.BooleanField(default=False, verbose_name='Nivel de Líquido de Frenos'),
        ),
        migrations.AlterField(
            model_name='checklistunidad',
            name='nivel_combustible',
            field=models.IntegerField(choices=[(0, 'Reserva (0%)'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], verbose_name='Nivel Combustible'),
        ),
    ]
